version: '3.0'
services:
  postgres:
    image: solzanir/postgres:9.6
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    networks:
      - georreferencia

  georreferencia:
    image: georreferencia:1.0
    container_name: georreferencia_app
    ports:
      - "8123:8123"
    networks:
      - georreferencia

networks:
   georreferencia: