version: '3.0'
services:
  mongodb:
    image: 'mongo:4.0.10'
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
      - "28017:28017"
    networks:
      - georreferencia
  
  mongo-express:    
    image: 'mongo-express:0.49.0'
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    ports:
      - "32881:8081"
    depends_on:
      - mongodb
    links:        
      - mongodb:mongo
    networks:
      - georreferencia      
  
  postgres:
    image: solzanir/postgres:9.6
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    networks:
      - georreferencia

networks:
   georreferencia: